### ISSUE TITLE
compatibilité safari

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#1]
n’ouvre pas sur la tablette iPad IOS 13.5.1
n’ouvre pas sur SAFARI ordi, OS 10.13
ouvre sur mon téléphone ios 14.1 mais plein d'artefacts

**Comment by yves-fonofone** [comment]
iPad : avec la dernière version de ios ça fonctionne. Mais pourquoi les 2 colonnes sont-elles inégales en largeur ?

**Comment by artificiel** [comment]
J'ai crée un sujet #16 pour établir la base qu'on veux supporter. à discuter là avant de faire des tests sur des plateformes qui ne sont pas à jour!

Pour la question des colonnes c'est que une est fixe et l'autre élastique; on va produire des exemples d'intégration du plugin différents pour éviter la confusion de ce côté. 

Je ferme ceci et continuons la discussion dans #16.
