### ISSUE TITLE
fonofone - panoramique, on a perdu la sortie gauche sur un son mono

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#102]

**Comment by OlivierRoss** [comment]
Ça ne le fait pas chez moi. Réglé?

**Comment by yves-fonofone** [comment]
Oups ! J’ai fermé trop rapidement cette « issue » : ça ne fonctionne toujours pas sur des sons mono.

Très bizz : sur le son « feuilles-vent le son est juste à droite.

Sur le son tic-aléa, le son est juste à gauche.

Yves





_____________

www.fonofone.org <http://www.fonofone.org/>
https://www.electrocd.com/resultats/daoust
 <https://www.electrocd.com/resultats/daoust>
