### ISSUE TITLE
fonction solo: doit ignorer le mixage fonoimage (uniquement tenir compte du volume de la zone)

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#103]
Quand on ouvre un fonofone, on doit pouvoir entendre le  son même si le curseur n'est pas dans la zone de ce son.

**Comment by yves-fonofone** [comment]
... en choisissant solo ?

**Comment by artificiel** [comment]
oui, solo doit désactiver l'impact du mixage du curseur
