### ISSUE TITLE
sons locaux

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#105]
Les sons qui apparaissent dans le dossier local sont liés à une zone spécifique: j'ai activé une zone, j'importe 1 ou quelques sons. Je vois ces sons dans le dossier local.
j'active une nouvelle zone, je ne vois plus de sons dans le dossier local. Si j'importe un nouveau son, il ne sera vu que quand j'active cette deuxième zone.
<img width="788" alt="Capture d’écran, le 2021-05-02 à 11 02 37" src="https://user-images.githubusercontent.com/80292072/116818139-bdc09d00-ab37-11eb-933d-6090ed9837f0.png">
<img width="723" alt="Capture d’écran, le 2021-05-02 à 11 02 50" src="https://user-images.githubusercontent.com/80292072/116818144-c6b16e80-ab37-11eb-978d-2666149541e8.png">

**Comment by artificiel** [comment]
la gestion des sons sera révisée
