### ISSUE TITLE
export/import

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#111]
j'ai exporté une activité. 

Quand je l'ai importée, les zones étaient bien en place mais celles en mode toucher étaient revenues en mode fondu/enchaîné. Et l'archive n'a pas gardé les sons.
<img width="976" alt="Capture d’écran, le 2021-05-07 à 17 36 24" src="https://user-images.githubusercontent.com/80292072/117510855-cc092180-af5a-11eb-9ed5-a832ab61ea4a.png">

**Comment by yves-fonofone** [comment]
Le comportement est bizarre :  si j'ai une zone de sélectionnée, alors le menu de sauvegarde est différent : on voit les sons de cette zone seule. S'il n'y a pas de sélection de zone, alors c'est la fenêtre qu'on voit dans la première image qui s'
<img width="1036" alt="Capture d’écran, le 2021-05-08 à 17 14 23" src="https://user-images.githubusercontent.com/80292072/117553677-e86f9180-b020-11eb-97b7-8b9d4a52b175.png">
ouvre où on ne voit aucun son à choisir.

**Comment by artificiel** [comment]
tel que discuté l'interface porte à confusion entre export de fonoimage et fonofone
