### ISSUE TITLE
inversion du son

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#113]
Ça ne fonctionne pas, la lecture du son reste à l'endroit. Et un drôle de truc biz se produit quand on clique sur la flèche : le son est brièvement transposé à la hauteur du varispeed.

**Comment by OlivierRoss** [comment]
Ça ne le fait pas chez moi. Réglé? J'ai aussi inversé la représentation graphique du son quand on inverse. Intéressant?
