### ISSUE TITLE
importation d'images

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#119]
Les nouvelles importations ne se gardent pas en mémoire.

**Comment by OlivierRoss** [comment]
Ok

**Comment by OlivierRoss** [comment]
Pour une seconde phase, il manquera un mécanisme pour supprimer les images.

**Comment by yves-fonofone** [comment]
Ça fonctionne pas de mon côté, je ne retrouve pas l'image quand j'ouvre à nouveau Ff.
