### ISSUE TITLE
à faire: ajouter fond grisé dans les zones (voir image issue #124)

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#126]

**Comment by OlivierRoss** [comment]
Ce ne sera simplement pas possible à cause de la technologie utilisée. Quand on mets de la couleur dans une ellipse, toutes celle qui sont derrière ne sont plus accessibles. Il faut absolument garder la transparence du background pour avoir accès à tous les niveaux.

**Comment by yves-fonofone** [comment]
Ok, je vois. De toute façon, je pense que c’est mieux comme ça, ça permettra d’ajouter des images dans le dessin de fond.

Y


_____________

www.fonofone.org <http://www.fonofone.org/>
https://www.electrocd.com/resultats/daoust
 <https://www.electrocd.com/resultats/daoust>
