### ISSUE TITLE
édition d'une zone

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#128]
Quand je crée une zone, le carré d'édition apparaît tout autour. Si j'allonge ou rétrécit la zone, le carré disparaît, je dois donc cliquer à nouveau sur la zone. Très agaçant.

Et bizarrement, le carré d'édition reste si je joue avec l'angle de la zone ou si je la déplace sur l'image.

**Comment by OlivierRoss** [comment]
Ok
