### ISSUE TITLE
variateur vitesse/hauteur (barre horizontale  mauve)

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#13]
1. Il faut faire les lignes exactement comme sur le dessin de François, en respectant rigoureusement l’espacement entre chacune,  avec une disposition différente selon qu’on a 1 barre ( | ), 2 barres (||) ou 3 ( |||). 
~~2. la gradation : 1 – 2 – 4 octaves. Actuellement c’est 2  -  4 –  8!
je vais faire une captation d’écran pour bien faire comprendre comment ça doit être calibré.~~ #28

**Comment by yves-fonofone** [comment]
et il faut revoir les proportions : beaucoup trop long en y.

**Comment by artificiel** [comment]
Les 3 versions de lignes doivent être fournies par françois.

**Comment by artificiel** [comment]
1 = -7 +7(fa#)
2 = -12 +12
3 = -24 + 24
aimant snap demi-ton

**Comment by artificiel** [comment]
ci-joint spec!

**Comment by artificiel** [comment]
[varispeed.pdf](https://github.com/hub-0-1/fonofone/files/6300945/varispeed.pdf)

**Comment by artificiel** [comment]
CORRECTION AU SPEC: changement de 7 vers 6 pour le nombre de division du mode 1 (le dessin et la logique était OK, seul le chiffre change).

[varispeed-rev2.pdf](https://github.com/hub-0-1/fonofone/files/6304851/varispeed-rev2.pdf)

**Comment by yves-fonofone** [comment]
Il y a une erreur dans le dessin 1 (+/ - 6 ) :  transpo descendante : c’est la première barre qui doit être blanche (do  - si )

_____________
www.fonofone.org <http://www.fonofone.org/>
https://www.electrocd.com/resultats/daoust <https://www.electrocd.com/resultats/daoust>

**Comment by OlivierRoss** [comment]
![image](https://user-images.githubusercontent.com/3496741/115166836-28c39b80-a083-11eb-9d30-0887535986f2.png)

Je n'ai pas encore appliqué les différentes hauteurs, mais dans le mode 3, ça donne quand même du stock plutôt collé. On va de l'avant?

**Comment by yves-fonofone** [comment]
C’est pas ça. François ne t’a pas donné les images?
m/resultats/daoust <https://www.electrocd.com/resultats/daoust>

**Comment by OlivierRoss** [comment]
Je me basais sur les specs de Alex : https://github.com/hub-0-1/fonofone/files/6304851/varispeed-rev2.pdf. On parle de 24 divisions de chaque côté du centre dans le mode 3. Donc 49 divisions. Sur un petit écran, ça fait tout un tas de divisions.

**Comment by yves-fonofone** [comment]
Et pour 2 et 3 :

:


_____________
www.fonofone.org <http://www.fonofone.org/>
https://www.electrocd.com/resultats/daoust <https://www.electrocd.com/resultats/daoust>

**Comment by OlivierRoss** [comment]
Je pense qu'il manque l'image ou le lien dans ton dernier commentaire.

**Comment by yves-fonofone** [comment]
Oui, mais c’est pour ça que c’est important qu’elles n’aient pas toutes la même taille et la même couleur.

C’est essentiellement les lignes blanches que l’oeil perçoit, ce qui fait que ça se lit bien, même sur le iPhone.
_____________
www.fonofone.org <http://www.fonofone.org/>
https://www.electrocd.com/resultats/daoust <https://www.electrocd.com/resultats/daoust>

**Comment by artificiel** [comment]
quand olivier dit "Je n'ai pas encore appliqué les différentes hauteurs" ça veut dire que les lignes ne sont pas "personnalisées" et veut seulement valider le nombre de divisions.

donc oui: le nombre de divisions est bon!

**Comment by yves-fonofone** [comment]
Je sais, j’avais bien compris. Je répondais au commentaire sur le grand nombre de divisions.

**Comment by yves-fonofone** [comment]
Oui, j'avais compris, je répondais au commentaire sur le grand nombre de divisions. 
<img width="566" alt="Capture d’écran, le 2021-04-18 à 20 25 34" src="https://user-images.githubusercontent.com/80292072/115167895-1c414200-a087-11eb-892c-22da6c16a6dc.png">
<img width="634" alt="Capture d’écran, le 2021-04-18 à 20 26 49" src="https://user-images.githubusercontent.com/80292072/115167902-24997d00-a087-11eb-9c1d-4c1b9f0f9c38.png">

**Comment by OlivierRoss** [comment]
Je viens de pousser une mise à jour pour le module de vitesse. Je pense que j'ai bien suivi les formules de Alex parce que pour les modes 2 et 3 ça semble fonctionner, mais pour le mode 1, je n'arrive pas au même pattern. C'est moi qui s'est trompé?

**Comment by yves-fonofone** [comment]
Je pense qu'il y avait une erreur dans le pattern d'Alex. Voici l'image prise directement du iPad. C'est donc le bon pattern.
<img width="590" alt="Capture d’écran, le 2021-04-18 à 21 24 07" src="https://user-images.githubusercontent.com/80292072/115169672-b1930500-a08c-11eb-81b2-2998e32c5b73.png">

**Comment by artificiel** [comment]
oui effectivement le dessin est erroné mais les équations sont bonnes, donc ton pattern | est bon!

**Comment by artificiel** [comment]
par-rapport à ce qui a été discuté au téléphone vs le comportement en mode II et III et les limites latérales, c'est je crois une question de marge faite en fonction d'accommoder le slider lorsqu'il est à fond:

<img width="792" alt="image" src="https://user-images.githubusercontent.com/2172370/115319826-9ee10480-a14e-11eb-8d33-ef365d5fad2a.png">
