### ISSUE TITLE
synchro entre le triangle et le parcours du son dans la forme d'onde

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#130]
Quand je change la portion du son avec le triangle, l’ajustement n’est pas immédiat : le curseur se rend au bout de la zone précédente avant de prendre la nouvelle position.

**Comment by OlivierRoss** [comment]
Lorsqu'on lance un son dans le Fonofone, il est joué jusqu'à la fin. Si on joue avec le triangle pendant le son, même si on rapetisse la zone de lecture, ce n'est que lorsqu'un nouveau son est lancé que sa durée sera rapetissée.

La pulsation ne fait donc que suivre le son qui joue dans le moment présent. Elle ne suit pas le son qui sera joué à la prochaine itération.

J'aurais donc tendance à dire que ceci n'est pas un bug.
