### ISSUE TITLE
triangle (fragmenteur) limites erronées (et ajustement du maximum)

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#14]
En bas complètement, le curseur sort du triangle, et la sélection continue de changer même un fois la limite atteinte.

**Comment by artificiel** [comment]
Il faut que le triangle-curseur soit bel et bien limité par le triangle, et une fois accoté, la limite du paramètre doit être atteinte. La limite de sélection doit être de 10ms.

**Comment by artificiel** [comment]
https://user-images.githubusercontent.com/2172370/110885285-96c2b900-82b4-11eb-8e9f-7c9d78333af0.mov

**Comment by OlivierRoss** [comment]
Fonctionnalité ok, look à travailler.
