### ISSUE TITLE
fonoimage -Que le nom de l’activité importée apparaisse au centre dans la barre d’activité 

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#155]
et qu'on puisse l'éditer.

**Comment by R3wi** [comment]
Ok c'est fait

**Comment by yves-fonofone** [comment]
Quand j'importe une activité, son nom n'apparaît pas.

**Comment by yves-fonofone** [comment]
Ok, c'est bon, je vois qu'il faut faire un rafraîchissement. Est-ce qu'il faudra toujours faire ça ??
