### ISSUE TITLE
fonoimage- On doit pouvoir détruire des images

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#158]

**Comment by OlivierRoss** [comment]
Ok, manque clairement un peu de design.

**Comment by yves-fonofone** [comment]
En fait, je vois que l'image qu'on met à la poubelle ne disparaît pas vraiment, elle revient quand on ouvre à nouveau fonoimage.

**Comment by OlivierRoss** [comment]
Les images qui reviennent sont des images par défaut. Je pourrais toutes les enlever (ou les remplacer) si désiré

**Comment by yves-fonofone** [comment]
Ok, je vois. Donc ce sera à nous au moment de rendre au public, de décider si on veut une image par défaut (sans doute que oui).Par contre, la poubelle est dans ce cas inutile. Moi, je l'imaginais pour toutes les images nouvelles qu'on importerait dans une activité et qu'on ne voudrait ps nécessairement garder au moment de la sauvegarde de l'activité.
Et je comprends aussi qu'une image importée ne sera conservée que si on sauvegarde l'activité. Logique...

**Comment by yves-fonofone** [comment]
Oui, sauf petit détail : sur google chrome les poubelles sont peu visibles, elles sont positionnées dans l'image.
