### ISSUE TITLE
Fonoimage- ajouter une icône pour supprimer le curseur (oreille)

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#162]
Voir le dessin de François dans l'issue 51

**Comment by yves-fonofone** [comment]
Oups ! plutôt issue 160

**Comment by OlivierRoss** [comment]
Je ne vois pas le bouton "supprimer l'oreille dans l'issue 160". Je ne vois que le fonofone et non le fonoimage. C'est normal?

**Comment by yves-fonofone** [comment]
Regarde plutôt l'image du # 161. L'image du # 160 représente un fonofone ouvert, CÀD qui occupe tout l'espace et voile les outils de fonoimage.

**Comment by OlivierRoss** [comment]
Quand on supprime, l'oreille, quel est le comportement attendu pour les zones qui étaient en mode "mix"?

**Comment by yves-fonofone** [comment]
Ça ne change rien, c'est juste qu'on ne la voit pas. Donc, si l'oreille était dans une zone mix, le son continue de jouer.

**Comment by OlivierRoss** [comment]
Ok
