### ISSUE TITLE
ajout du hp dans la zone jaune

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#165]
1-Le changement d'état n'apparaît que lorsqu'on quitte la zone, ce qui est source de confusion.

2. Quand on ouvre une zone, son état est mix par défaut. Est-il possible que ce hp n'apparaisse que lorsqu'on change pour le mode toucher ? (cercle jaune).

**Comment by OlivierRoss** [comment]
Ok
