### ISSUE TITLE
Nom de son d'enregistrement de performance

### ISSUE THREAD

**Issue by artificiel** [hub-0-1/fonofone#17]
plutôt que `"session__sdsdsd_.webm"`, le nom d'un enregistrement devrait être `"<nom de l'activité> <AAAA-MM-JJ HH:MM:SS>.webm"` (ou .wav, idéalement)

**Comment by OlivierRoss** [comment]
Pour la date j'ai mis toLocaleString(). Est-ce que tu tiens à ton format ou on laisse ça international?

**Comment by artificiel** [comment]
c'est parfait toLocaleString()
