### ISSUE TITLE
Ajouter un bouton de réinitialisation (flèche à droite du import/export)

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#3]
bouton "solo" 
boutons fondu/enchainé et toucher
bouton de réinitialisation de l'activité

**Comment by artificiel** [comment]
NOTE: Les boutons solo et fondu/enchaînés ne sont pas actifs en dehors d'un fonoimage.

Pour réinitialiser, ajouter un bouton à gauche des import/export, qui a comme effet de recharger la config telle qu'initialement lue.

**Comment by OlivierRoss** [comment]
Ok
