### ISSUE TITLE
l'aimant du métronome doit snapper le slider swing selon une progression précise

### ISSUE THREAD

**Issue by artificiel** [hub-0-1/fonofone#30]
donc avec l'aimant activé, le slider swing peut juste être extrême gauche, extrême droite, et centre.

le slider noise n'est pas affecté par l'aimant, ni le slider BPM.

**Comment by OlivierRoss** [comment]
Ok

**Comment by yves-fonofone** [comment]
Il faudra revoir ce snap. Alex, j'aimerais un échelle comme celle-ci :
<img width="354" alt="Capture d’écran, le 2021-04-07 à 14 53 56" src="https://user-images.githubusercontent.com/80292072/113919057-258dfd00-97b1-11eb-90e9-def7f5229757.png">

**Comment by artificiel** [comment]
1) si la gradation est “toujours snap” on devrait faire un radio-bouton plutôt qu’un slider.

2) j’avoue ne pas être friand des dessins de notes... d’autant plus qu’on a réussi à éviter toute représentation conventionnelle! 

	a) est-ce que des ratios pourraient être utilisés? selon ta grille ce serait:

		1:1  2:1  3:1  4:1  5:1

	b) ou encore, la durée proportionelle de la première note

		1/2  2/3  3/4  4/5  5/6

j’aime mieux (a), qui commence à 1:1. ça ressemblerait à ceci:

<img width="279" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/2172370/114485239-941bf200-9bd9-11eb-8723-7909ca9b0e24.png">

on pourrait laisser tomber le :1 et avoir juste 1 2 3 4 5

**Comment by yves-fonofone** [comment]
OK pour les boutons, plus logique. 
Pour les valeurs, autre possibilité, peut-être plus facile à comprendre et à expliquer pour le prof : 1+1   2+1   3+1  (4+1)   5+1
Parenthèses : le quintolet n'est peut-être pas nécessaire. C'est bien subtil, à moins qu'on veuille faire du Stockhausen.

**Comment by artificiel** [comment]
???

**Comment by artificiel** [comment]
il manquait mon image!

<img width="582" alt="PastedGraphic-8" src="https://user-images.githubusercontent.com/2172370/114492749-2f679400-9be7-11eb-9407-22acf888824d.png">

**Comment by yves-fonofone** [comment]
AHHHH ! Tout s'éclaire...   Je vais communiquer ça à François

**Comment by artificiel** [comment]
je pense que 5:1 devrait être plus squeezé

<img width="580" alt="image" src="https://user-images.githubusercontent.com/2172370/114496742-99376c00-9bee-11eb-89f4-8d4e68774471.png">

**Comment by yves-fonofone** [comment]
oui, on voit mieux la progression.

**Comment by artificiel** [comment]
OK donc on attend les images de françois pour cela
