### ISSUE TITLE
fonoIMAGE-zones, ellipse<->rectangle

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#35]
la zone devrait être carrée avec la possibilité de l'arrondir (comme dans adobe XD)

**Comment by artificiel** [comment]
Je comprend ce que tu veux dire, mais à quoi exactement fais-tu référence "dans XD"? je ne trouve pas cet exemple.

**Comment by OlivierRoss** [comment]
Fonctionnalité caduc
