### ISSUE TITLE
fonoIMAGE-ajout de zones

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#37]
Il ne faudrait pas devoir re-cliquer sur l'icône zone à chauqe fois qu'on veut en ajouter une. Très fastidieux.
L'icône devrait s'illuminer quand on la choisit (la fonction devient active et le reste tant qu'on ne la désactive pas, soit en cliquant dessus, soit en quittant le mode édition.

**Comment by artificiel** [comment]
#58
