### ISSUE TITLE
fonoIMAGE- son, bug

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#38]
Encore une fois, il y a une logique inversée avec le crayon. 
1. le crayon sert à passer du mode jeu au mode édition, pas à couper le son. Il faudra probablement ajouter un bouton "mute"
2. Et le curseur de jeu doit être toujours visible, à moins qu'on veuille le rende invisible (icône spéciale pour ça).

**Comment by artificiel** [comment]
#58
