### ISSUE TITLE
la fonction boucle doit être active par défaut

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#4]
Doit être activée par défaut.

**Comment by OlivierRoss** [comment]
Est-ce qu'elle doit toujours être activée par défaut? Pour l'instant c'est seulement une configuration. Quand on exporte le fonofone, le paramètre "loop" est sauvegardé comme il est.

**Comment by artificiel** [comment]
OK donc disons qu'on parle d'une configuration "usine" "par défaut", dans cette configuration la loop doit être active. De là, la configuration se sauvera selon l'état du piton au moment de l'exportation (comme actuellement).

(Dans les faits il y a toujours une configuration, mais la configuration "usine" risque de servir souvent de point de départ).
