### ISSUE TITLE
fono-IMAGE, mode piqué

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#42]
En mode piqué, l'icône de jeu dans la zone ne devrait être fixe, ou du moins ne pas pouvoir sortir de la zone. Mais je préfère fixe : si on veut ajuster le volume, on revient dans fonofone.

**Comment by artificiel** [comment]
ceci a été couvert lors de la discussion sur la simplification de l'interface #58, et le verdict est que l'icône centrale des zones piqué ne peux être excentrique, que la distance du clic au centre n'affecte pas le volume, et que l'icône centrale est une télécommande "on-off" du bouton play dans les outils, donc se comporte exactement comme ce bouton play (options de loop, direction, etc.).
