### ISSUE TITLE
fono-Images icônes bibliothèque image et zones

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#47]
Les icônes zones et bibliothèque d'images devraient toujours être présentes. On ne doit pas avoir à repasser par le crayon.

**Comment by yves-fonofone** [comment]
Finalement, non. Normal qu'ils apparaissent seulement quand on est en mode édition (crayon).

**Comment by artificiel** [comment]
En relation avec #58, il faut que l'icône de changement d'image apparaisse seulement quand on "débarre" le truc (états 2 et 3).

**Comment by artificiel** [comment]
intégré au fonostate4 #58
