### ISSUE TITLE
boutons on/off

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#5]
activés, ils sont brillants : éliminer le carré blanc (voir Ff sur tablette)

**Comment by artificiel** [comment]
Il faut fournir les icones on/off à olivier (on ne peux pas les "voler" de la tablette). Est-ce possible de vérifier avec François si ces items sont exportables du Flow? Si oui indiquer à Olivier comment les prendre, sinon les créer

**Comment by yves-fonofone** [comment]
Je transmets à François.

**Comment by artificiel** [comment]
duplicate #52
