### ISSUE TITLE
importer-exporter Fonoimage (vs fonofones) -- banque de son commune?

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#50]
Je n'y comprends rien. Pourquoi les icônes sont-elles doublées ? Tout ça n'est pas du tout intuitif. Penser à l'enfant de 2è année...

**Comment by artificiel** [comment]
Il faut revenir sur ce sujet: comment sont gérées les exportations de fonoimage (vs les N fonofones inclus). il est sans doute logique de réfléchir à une banque "collective" pour tout les fonofones d'un fonoimage (sinon, possibilité de doublons, et possiblement laborieux de traiter l'export si chaque zone contient plusieurs sons)

**Comment by yves-fonofone** [comment]
Tu veux dire au niveau des sons? Question bien naïve : comme  les sons dans des banques sur le site, est-ce que ça pourrait être juste une adresse qui permet d'aller les rechercher ? Il y a le problème de "mes sons" s'ils sont sauvegardés seulement local.  Je suis perdu dans la technique de ces questions d'import/export, manifestement pas très simple.

**Comment by artificiel** [comment]
Oui, au niveau des sons: présentement un .fnfn contient l'état des différents paramètres, les sons "fournis" par le créateur d'activité, et les sons que l'utilisateur aura choisi de garder à l'exportation d'un fonofone.

Si on applique directement la logique, un .fonoimage serait une collection zones-fonofones, donc de .fnfn (avec les infos de zones et l'image en plus).

Mais (a) si le même son est dans N zones, il sera sauvé en N copies (inutiles) mais surout (b) si on rajoute un son (micro par exemple) dans une zone, on veux que ce son soit aussi disponible dans les autres zones!

Donc la banque de son d'un fonoimage devrait être "globale", au moins au niveau de l'import-export (dans les faits, peut-être qu'elle "télécommande" les N banques fonofones, mais concrètemeent on veux 1 download par instance de son, et l'accès "global' aux sons persos entre les zones).

Et quand on exporte un fonoimage, le (nouveau) dialogue d'exportation liste tous les sons et offre de les exporter ou pas de façon globale (et pas un dialog par zone/fonofone).

La logique des sons fournis en URL et maintenus à l'état "pur" (pas de crop) sont préservés comme des URL.

**Comment by yves-fonofone** [comment]
"et les sons que l'utilisateur aura choisi de garder à l'exportation d'un fonofone"
Est-ce que ça signifie que quand il recharge son activité, il ne verrait plus l'ensemble des sons programmés pour l'activité par le prof ?

**Comment by artificiel** [comment]
la proposition actuelle distingue 2 types de sons: en ligne (des URL téléchargés à la demande) et "intégrés" (contenus à même le fichier .fnfn).

selon le principe actuel, si le son provient d'une banque en ligne (url) il va rester disponible; si c'est un son intégré à même la configuration, et que l'utilisateur choisi activement de retirer le son de la configuration lors d'une sauvegarde, il sera retiré.

on peux imaginer un mécanisme pour "verrouiller" des options, mais ce mécanisme doit être réfléchi en fonction des outils en ligne (phase 3) et du principe de hiérarchie des utilisateurs, groupes, etc. en mode "autonome", une fois l'activité chargée puis sauvegardée sur le disque, elle "appartient" à l'utilisateur local.

**Comment by artificiel** [comment]
pour le moment, #116 et #117
