### ISSUE TITLE
fonofone-fonctions de jeu

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#53]
Faire **exactement** comme dans la planche de François. La fenêtre doit donc être plus grosse, les boutons plus gros et la forme d'onde occuper toute la largeur de la fenêtre.

**Comment by artificiel** [comment]
est-ce que tu peux prendre un screenshot avec ce que tu vois et la référence XD à côté? (il y a beaucoup de facteurs de "zoom" possibles dans un browser web faut être sûr de celui qu'on travaille)

**Comment by yves-fonofone** [comment]
<img width="359" alt="Capture d’écran, le 2021-04-07 à 09 59 31" src="https://user-images.githubusercontent.com/80292072/113879136-39713900-9788-11eb-9eb3-a8ea02e763b0.png">

**Comment by yves-fonofone** [comment]
OK.

Petite question : ARTIFICIEL c’est incorporé ? J’ai versé un cachet de 1500 $ à Artificiel en 2020. Si c'est pas incorporé, j’aurais dû émettre un feuillet fiscal.

Yves
_____________
www.fonofone.org <http://www.fonofone.org/>
https://www.electrocd.com/resultats/daoust <https://www.electrocd.com/resultats/daoust>

**Comment by yves-fonofone** [comment]
![Capture d’écran, le 2021-04-07 à 15 12 14](https://user-images.githubusercontent.com/80292072/113922616-7f90c180-97b5-11eb-9e79-19d73af7b64e.png)
<img width="359" alt="Capture d’écran, le 2021-04-07 à 09 59 31" src="https://user-images.githubusercontent.com/80292072/113922695-99320900-97b5-11eb-8c31-f97597dd1788.png">
