### ISSUE TITLE
fonoimage - bouton solo - fonction audio

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#57]
Imaginons qu'il y a plein de sons qui jouent dans la zone image mais on veut change de son pour une zone, ou juste ajuster des paramètres. On ouvre fonofone. Le bouton solo permet de couper tous les sons sauf celui qu'on édite.
Dans certains cas, on va préférer entendre tou les sons, par exemple s,il s'agit juste d'ajuster un peu le volume d,un son particulier.

**Comment by artificiel** [comment]
proposition en lien avec #81 


<img width="971" alt="image" src="https://user-images.githubusercontent.com/2172370/114584273-7fc70c00-9c50-11eb-823a-2a7ea2c3b364.png">

**Comment by artificiel** [comment]
et aussi, en mode solo: la zone sélectionné n'est pas affectée par le mixage des zones — elle joue à 100% comme si c'était un fonofone plugin.
