### ISSUE TITLE
fonoimage: simplification de l'ergonomie des fonctions

### ISSUE THREAD

**Issue by artificiel** [hub-0-1/fonofone#58]
j'ai un peu de misère à me retrouver entre le crayon, et l'édition, vs l'outil "zone (recoupe #56 #55 #36).

j'ai une proposition qui simplifie l'ergonomie avec seulement 3 états et 2 boutons. ci-joint en PDF. la proposition a aussi l'avantage d'être progressive (donc un "apprentissage obligatoire").

et je rassemble les fonctions en haut à gauche où c'est cohérent (premier point de contact) — je n'aime pas la position actuelle du crayon.

[fonostate.pdf](https://github.com/hub-0-1/fonofone/files/6260946/fonostate.pdf)

**Comment by yves-fonofone** [comment]
Hum ! un peu dur à suivre. J'aurais besoin de visualiser tout ça.
D'Accord pour les boutons à gauche.

**Comment by artificiel** [comment]
voici une v2 qui tient compte de notre discussion de ce matin, incluant le retrait du mode aveugle (qui n'est pas essentiel, donc on coupe!), donc deux seuls boutons: HP et cadenas (plus de crayon, ni de "zone").

[fonostate2.pdf](https://github.com/hub-0-1/fonofone/files/6267975/fonostate2.pdf)

est-ce complet?

**Comment by yves-fonofone** [comment]
Oui, ça me semble complet.

Ne pas oublier les fonctions SOLO.

Aussi : il y a la fonction permettant de désaxer le point ff dans une zone, qui n’est pas développé actuellement.


_____________
www.fonofone.org <http://www.fonofone.org/>
https://www.electrocd.com/resultats/daoust <https://www.electrocd.com/resultats/daoust>

**Comment by artificiel** [comment]
OK on va confirmer tout ça vendredi autour de la table.
