### ISSUE TITLE
organisation dynamique en colonnes si la largeur du DIV le permet

### ISSUE THREAD

**Issue by artificiel** [hub-0-1/fonofone#66]
si la largeur du DIV fonofone dépasse une certaine limite, des colonnes doivent apparaître et les outils se présenter en 2 (ou 3) colonnes. (à noter que dans fonoimage la largeur totale pourra être utilisée).

EDIT: à noter que la zone du son prend toute la largeur [(voir page 4 du XD)](https://xd.adobe.com/view/72800d73-ba9e-4b27-bd87-362a1c2f7098-27d3/screen/bed75f66-4dae-45d9-bde0-292fb0273a40/)

**Comment by OlivierRoss** [comment]
Ok
