### ISSUE TITLE
renommer les sons

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#7]
Ça semble pas possible. Je vois pas de menu pour ça.

**Comment by artificiel** [comment]
Tu parles de quel son / quelle partie de l'interface ici?

**Comment by yves-fonofone** [comment]
En fait, je ne vois même pas où et comment on sauvegarde un son qu'on vient de créer. Et les sons importés, on ne peut pas les renommer.
Tout cet aspect de sauvegarde et rappel est confus : il y a l'icône d'archives et les icônes d'import/export en haut à droite. Vraiment confus tout ça.
