### ISSUE TITLE
métronome-valeurs de snap (potentiomètre supérieur)

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#75]
Ma proposition : on supprime le glissé, on est juste en snap (donc on peut supprimer l'aimant).
Il y aurait 4 valeurs, à ajuster très précisément (voir l'image)
<img width="525" alt="Capture d’écran, le 2021-04-09 à 16 26 27" src="https://user-images.githubusercontent.com/80292072/114237431-1776e280-9951-11eb-8ae5-ecbe933ebdd9.png">

**Comment by yves-fonofone** [comment]
Précisions : chiffres ou figures de notes (petite préférence pour les notes).

Attention dans la calibration : si le métronome est à 60 on garde toujours la même valeur globale de noire pour les 4 positions.
(Désolé, je ne sais pas exprimer ça en math).

**Comment by artificiel** [comment]
voir #30
