### ISSUE TITLE
sélection wavesurfer doit être bidirectionnelle avec le triangle

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#9]
La barre grise de sélection ne se rend pas tout à fait au début du son.
On peut la déplacer avec le doigt ou la souris, mais aucun effet sur le son, le curseur du fragmenteur (triangle) ne suit pas.

**Comment by OlivierRoss** [comment]
J'ai l'impression que la barre va au début du son. Sur quel appareil et sur quel browser est-ce que la barre ne va pas au début du son?

Pour l'effet de la barre de sélection sur le fragmenteur, le code n'a pas été pensé pour ça et la librairie utilisée ne semble pas être faite pour ça. Comme c'est un bon projet, on confirme que c'est une fonctionnalité nécessaire?

**Comment by yves-fonofone** [comment]
1. Je vais vérifier. Peut-être sur iPad.
2. Fonctionnalité nécessaire : oui.

**Comment by artificiel** [comment]
2. dans le prototype grain qui est en ligne je n'ai effectivement pas intégré cette connexion mais j'avais testé le callback wavesurfer "region-updated", et de là tu peux récupérer le .start et .end de la "region" à chaque fois qu'elle change.

**Comment by OlivierRoss** [comment]
Ok
