### ISSUE TITLE
varispeed - calibration

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#93]
La calibration n'est pas bonne, les sauts de demi-tons ne sont pas égaux.

**Comment by yves-fonofone** [comment]
La calibration vers la gauche (vers les graves ) est OK. C'est vers le haut que ça va pas. L"octave (dernière barre) est correcte, c'est comme si plus on monte, plus la relation se corrige, mais pas complètement.

Est-ce les ratios ou la position des lignes? C'est trop petit pour qu'on puisse bien voir.

**Comment by artificiel** [comment]
dup #149
