### ISSUE TITLE
calcul du mix fonoimage sur mouvement de curseur OU de zone

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#98]
Situation : 2 zones qui se chevauchent, donc j'entends 2 sons. Si je déplace une des zones, il n'y a pas de changement dans les sons, même si je glisse complètement la zone hors du curseur. Pour que le nouvel état sonore s'entende, je dois cliquer sur le curseur. Idem dans le sens contraire.

**Comment by artificiel** [comment]
le calcul du mix doit être effectué lorsque le curseur bouge, ou lorsqu'une zone bouge.

**Comment by OlivierRoss** [comment]
Ça ne le fait pas chez moi. Toujours d'actualité?
