### ISSUE TITLE
difficulté de saisir une zone pour la déplacer

### ISSUE THREAD

**Issue by yves-fonofone** [hub-0-1/fonofone#99]
C'est pas facile.... Il faut vraiment voir la souris changer d'état, sinon on dessine une nouvelle zone. Ce sera pas évident sur iPad ou TNI. Est-ce que ce sera plus facile quand la représentation de la zone sera complétée ? Pourra t-on alors saisir la zone de l'intérieur ?

**Comment by artificiel** [comment]
on ne peux pas saisir par le centre car ça va être compliqué en cas d'overlaps! mais la "sensibilité" de la sélection est ajustable (#86)
